import "./globals.css"
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import { ClerkProvider } from "@clerk/nextjs"
import { ModelProvider } from "@/components/model-provider"
const inter = Inter({ subsets: ["latin"] })
import Image from "next/image"
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`inter.className`}>
          <ModelProvider />
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}
